CREATE SEQUENCE "EMERGIR_DIGITAL".SEQ_EVOLUCOES_CLINICAS
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE CACHE 1;

CREATE TABLE "EMERGIR_DIGITAL".EVOLUCOES_CLINICAS
(
    IDT_EVOLUCOES_CLINICAS BIGINT       NOT NULL DEFAULT nextval('"EMERGIR_DIGITAL".SEQ_EVOLUCOES_CLINICAS'::regclass),
    DESCRICAO              VARCHAR(500) NOT NULL,
    DT_REGISTRO            DATE         NOT NULL,
    IDT_PACIENTE           BIGINT       NOT NULL,
    CONSTRAINT PK_EVOLUCOES_CLINICAS PRIMARY KEY (IDT_EVOLUCOES_CLINICAS),
    CONSTRAINT FK_EVOLUCOES_CLINICAS_PACIENTE FOREIGN KEY (IDT_PACIENTE)
        REFERENCES "EMERGIR_DIGITAL".PACIENTES (IDT_PACIENTES)
);

CREATE SEQUENCE "EMERGIR_DIGITAL".SEQ_FICHAS_ANAMNESE
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE CACHE 1;

CREATE TABLE "EMERGIR_DIGITAL".FICHAS_ANAMNESE
(
    IDT_FICHAS_ANAMNESE BIGINT       NOT NULL DEFAULT nextval('"EMERGIR_DIGITAL".SEQ_FICHAS_ANAMNESE'::regclass),
    DESCRICAO           VARCHAR(500) NOT NULL,
    DT_REGISTRO         DATE         NOT NULL,
    IDT_PACIENTE        BIGINT       NOT NULL UNIQUE,
    CONSTRAINT PK_FICHAS_ANAMNESE PRIMARY KEY (IDT_FICHAS_ANAMNESE),
    CONSTRAINT FK_FICHAS_ANAMNESE_PACIENTE FOREIGN KEY (IDT_PACIENTE)
        REFERENCES "EMERGIR_DIGITAL".PACIENTES (IDT_PACIENTES)
);