CREATE SEQUENCE "EMERGIR_DIGITAL".SEQ_AVALIACOES_PSICOLOGICAS
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE CACHE 1;

CREATE TABLE "EMERGIR_DIGITAL".AVALIACOES_PSICOLOGICAS
(
    IDT_AVALIACOES_PSICOLOGICAS BIGINT        NOT NULL DEFAULT nextVal('"EMERGIR_DIGITAL".SEQ_AVALIACOES_PSICOLOGICAS'::regclass),
    NOME_PACIENTE               VARCHAR(100)  NOT NULL,
    IDADE                       BIGINT        NOT NULL,
    ENCAMINHAMENTO              VARCHAR(80)   NOT NULL,
    VALOR                       NUMERIC(5, 2) NOT NULL,
    FORMA_PAGAMENTO             VARCHAR(20)   NOT NULL,
    TEM_CONTRATO                BOOLEAN       NOT NULL,
    ATENDIMENTOS                BIGINT        NOT NULL,
    SITUACAO_AVALIACAO          VARCHAR(20)   NOT NULL,
    DATA_INICIAL                DATE          NOT NULL,
    DATA_FINAL                  DATE,
    DATA_DEVOLUTIVA             DATE,
    AVALIACAO_GOOGLE            BOOLEAN       NOT NULL,
    IDT_PACIENTE                BIGINT,
    CONSTRAINT PK_AVALIACOES_PSICOLOGICAS PRIMARY KEY (IDT_AVALIACOES_PSICOLOGICAS),
    CONSTRAINT PK_AVALIACOES_PSICOLOGICAS_PACIENTE FOREIGN KEY (IDT_PACIENTE)
        REFERENCES "EMERGIR_DIGITAL".PACIENTES (IDT_PACIENTES)
        ON DELETE SET NULL
);